const url = 'http://localhost:3002/api/';
const login = 'user/login';
const checkAuth = 'user/me';
const register = 'user/register';
const auth_url = 'http://localhost:3002/api/auth';
const facebook ='facebook';
const google = 'google';
const viewAllTutors = 'viewAllTutor';
const viewDetailTutor = 'viewDetailTutor';
const showskills = 'showskills';
const editInfor = 'editInfor';
const updateSkill = 'updateSkill';
const getInfo = 'user/infor';
const deleteSkill = 'deleteSkill';
export {url, getInfo, deleteSkill, viewAllTutors,updateSkill, viewDetailTutor, editInfor,showskills,login,checkAuth,register,auth_url, facebook, google};